name: CI/CD Serverless Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Lint Terraform code
        run: terraform fmt -check

      - name: Validate Terraform
        run: |
          cd terraform
          terraform init -input=false
          terraform validate

      - name: Lint Python (Lambda)
        run: |
          pip install black flake8
          black --check lambda_nyc_extractor/lambda_function.py
          flake8 lambda_nyc_extractor/lambda_function.py

      - name: Package Lambda Code
        run: |
          cd lambda_nyc_extractor
          zip ../terraform/lambda_package/lambda_nyc_extractor_package.zip lambda_function.py

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false

      - name: Terraform Apply (Deploy to AWS)
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: terraform
        run: terraform apply -auto-approve -input=false
